module.exports = {
  projects: [
    '<rootDir>/apps/consolidator',
    '<rootDir>/libs/ui',
    '<rootDir>/libs/ui/material',
    '<rootDir>/libs/perun/services',
    '<rootDir>/libs/perun/models',
    '<rootDir>/libs/perun/tokens',
    '<rootDir>/libs/perun/utils',
    '<rootDir>/libs/perun/urns',
    '<rootDir>/libs/ui/alerts',
    '<rootDir>/apps/admin-gui',
    '<rootDir>/libs/perun/openapi',
    '<rootDir>/apps/statistics',
    '<rootDir>/libs/config',
    '<rootDir>/libs/general',
    '<rootDir>/libs/perun/components',
    '<rootDir>/libs/perun/facility-services-config',
    '<rootDir>/libs/config/table-config',
    '<rootDir>/libs/perun/pipes',
    '<rootDir>/apps/user-profile',
    '<rootDir>/libs/perun/animations',
    '<rootDir>/libs/perun/directives',
    '<rootDir>/libs/dialogs',
  ],
};
