/**
 * Perun RPC API
 * Perun Remote Procedure Calls Application Programming Interface
 *
 * The version of the OpenAPI document: 3.10.0
 * Contact: perun@cesnet.cz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type AppState = 'NEW' | 'VERIFIED' | 'APPROVED' | 'REJECTED';

export const AppState = {
    NEW: 'NEW' as AppState,
    VERIFIED: 'VERIFIED' as AppState,
    APPROVED: 'APPROVED' as AppState,
    REJECTED: 'REJECTED' as AppState
};

