/**
 * Perun RPC API
 * Perun Remote Procedure Calls Application Programming Interface
 *
 * The version of the OpenAPI document: 3.10.0
 * Contact: perun@cesnet.cz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type FacilityPropagationState = 'OK' | 'ERROR' | 'PROCESSING' | 'NOT_DETERMINED';

export const FacilityPropagationState = {
    OK: 'OK' as FacilityPropagationState,
    ERROR: 'ERROR' as FacilityPropagationState,
    PROCESSING: 'PROCESSING' as FacilityPropagationState,
    NOTDETERMINED: 'NOT_DETERMINED' as FacilityPropagationState
};

