/**
 * Perun RPC API
 * Perun Remote Procedure Calls Application Programming Interface
 *
 * The version of the OpenAPI document: 3.10.0
 * Contact: perun@cesnet.cz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type TaskResultStatus = 'DONE' | 'ERROR' | 'DENIED' | 'WARNING';

export const TaskResultStatus = {
    DONE: 'DONE' as TaskResultStatus,
    ERROR: 'ERROR' as TaskResultStatus,
    DENIED: 'DENIED' as TaskResultStatus,
    WARNING: 'WARNING' as TaskResultStatus
};

