/**
 * Perun RPC API
 * Perun Remote Procedure Calls Application Programming Interface
 *
 * The version of the OpenAPI document: 3.10.0
 * Contact: perun@cesnet.cz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * statuses of a member in a Vo
 */
export type VoMemberStatuses = 'VALID' | 'INVALID' | 'SUSPENDED' | 'EXPIRED' | 'DISABLED';

export const VoMemberStatuses = {
    VALID: 'VALID' as VoMemberStatuses,
    INVALID: 'INVALID' as VoMemberStatuses,
    SUSPENDED: 'SUSPENDED' as VoMemberStatuses,
    EXPIRED: 'EXPIRED' as VoMemberStatuses,
    DISABLED: 'DISABLED' as VoMemberStatuses
};

