export * from './attributesManager.service';
import { AttributesManagerService } from './attributesManager.service';
export * from './authzResolver.service';
import { AuthzResolverService } from './authzResolver.service';
export * from './databaseManager.service';
import { DatabaseManagerService } from './databaseManager.service';
export * from './extSourcesManager.service';
import { ExtSourcesManagerService } from './extSourcesManager.service';
export * from './facilitiesManager.service';
import { FacilitiesManagerService } from './facilitiesManager.service';
export * from './groupsManager.service';
import { GroupsManagerService } from './groupsManager.service';
export * from './membersManager.service';
import { MembersManagerService } from './membersManager.service';
export * from './ownersManager.service';
import { OwnersManagerService } from './ownersManager.service';
export * from './registrarManager.service';
import { RegistrarManagerService } from './registrarManager.service';
export * from './resourcesManager.service';
import { ResourcesManagerService } from './resourcesManager.service';
export * from './servicesManager.service';
import { ServicesManagerService } from './servicesManager.service';
export * from './tasksManager.service';
import { TasksManagerService } from './tasksManager.service';
export * from './usersManager.service';
import { UsersManagerService } from './usersManager.service';
export * from './utils.service';
import { UtilsService } from './utils.service';
export * from './vosManager.service';
import { VosManagerService } from './vosManager.service';
export const APIS = [AttributesManagerService, AuthzResolverService, DatabaseManagerService, ExtSourcesManagerService, FacilitiesManagerService, GroupsManagerService, MembersManagerService, OwnersManagerService, RegistrarManagerService, ResourcesManagerService, ServicesManagerService, TasksManagerService, UsersManagerService, UtilsService, VosManagerService];
